# Compiler settings
CXX := g++
CPPFLAGS := -Iinclude -MMD -MP
CXXFLAGS := -std=c++20 -Wall -Wextra -O2

# Target executable name
TARGET := build/my_clt

# Source files
SRCS := $(wildcard src/*.cpp)

# Object files (replaces .cpp with .o)
OBJS := $(SRCS:src/%.cpp=build/%.o)

# Dependency files generated by the compiler
DEPS := $(OBJS:.o=.d)

# Default rule to build the executable
$(TARGET): $(OBJS)
	$(CXX) $^ -o $@

# Create the build directory
build:
	mkdir -p build

# Rule to compile source files into object files and compiles only if build exists
build/%.o: src/%.cpp | build 
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $< -o $@ 

.PHONY: clean

# Clean rule to remove compiled files
clean:
	rm -f $(OBJS) $(DEPS) $(TARGET)

# Include the generated dependency files
-include $(DEPS)